### ISSUE TITLE
ios与安卓连麦出现ios没有声音内有log

### ISSUE THREAD

**Issue by shlowdy** [ksvc/KSYRTCLive_iOS#1]
log
2016-11-21 20:09:56.247896 KSYRTCStreamerDemo[379:133034] [aurioc] 889: failed: -66635 (enable 3, outf< 1 ch,  44100 Hz, Int16> inf< 1 ch,  44100 Hz, Int16>)

安卓连ios时第一次会出现ios没有声音安卓有声音
第一次必现随后的偶尔出现
ios互连会偶尔出现

总之就是ios端会出现播不出声音的情况

ios是1.8.8版本 安卓是最新版

**Comment by yulin6666** [comment]
连麦ios的底层是通过audiounit实现的，你的app里是不是有audiounit相关的逻辑？

**Comment by shlowdy** [comment]
运行的是你们的demo 并没有我的app哈
会不会是跟设备有关 我用的iPod touch

**Comment by shlowdy** [comment]
经过最新测试与设备无关
在iphone6plus上出现同样问题
ios9和ios10上一样
最新的1.9.0sdk

**Comment by yulin6666** [comment]
没有声音是主播端？辅播端么？还是观众端？

**Comment by shlowdy** [comment]
不是观众端 是连麦的两端
你们拿一个安卓设备跟一个ios设备试一试就知道了 安卓呼叫ios
必现

**Comment by fnglin** [comment]
Android连麦需要推流才能把声音推出去，这个问题我们下个版会改进，所以请确认一下你的Android设备是否有开始推流

**Comment by shlowdy** [comment]
好 那我等你们发新版本了再测一下
也建议你们多做一下ios安卓两端连麦的测试
